// Code generated by xf. DO NOT EDIT.

package proapi

import (
	"github.com/77d88/go-kit/plugins/xapi/server/xhs"
	dbAutoMigrate "github.com/77d88/go-kit/server/admin_pro/proapi/db/autoMigrate"
	dbDbModels "github.com/77d88/go-kit/server/admin_pro/proapi/db/dbModels"
	dbInitDataRows "github.com/77d88/go-kit/server/admin_pro/proapi/db/initDataRows"
	dictDel "github.com/77d88/go-kit/server/admin_pro/proapi/dict/del"
	dictInfo "github.com/77d88/go-kit/server/admin_pro/proapi/dict/info"
	dictList "github.com/77d88/go-kit/server/admin_pro/proapi/dict/list"
	dictSave "github.com/77d88/go-kit/server/admin_pro/proapi/dict/save"
	dictTypes "github.com/77d88/go-kit/server/admin_pro/proapi/dict/types"
	menuDel "github.com/77d88/go-kit/server/admin_pro/proapi/menu/del"
	menuInfo "github.com/77d88/go-kit/server/admin_pro/proapi/menu/info"
	menuList "github.com/77d88/go-kit/server/admin_pro/proapi/menu/list"
	menuMenu "github.com/77d88/go-kit/server/admin_pro/proapi/menu/menu"
	menuSave "github.com/77d88/go-kit/server/admin_pro/proapi/menu/save"
	permissionDel "github.com/77d88/go-kit/server/admin_pro/proapi/permission/del"
	permissionDisable "github.com/77d88/go-kit/server/admin_pro/proapi/permission/disable"
	permissionEnable "github.com/77d88/go-kit/server/admin_pro/proapi/permission/enable"
	permissionInfo "github.com/77d88/go-kit/server/admin_pro/proapi/permission/info"
	permissionList "github.com/77d88/go-kit/server/admin_pro/proapi/permission/list"
	permissionSave "github.com/77d88/go-kit/server/admin_pro/proapi/permission/save"
	roleDel "github.com/77d88/go-kit/server/admin_pro/proapi/role/del"
	roleDisable "github.com/77d88/go-kit/server/admin_pro/proapi/role/disable"
	roleEnable "github.com/77d88/go-kit/server/admin_pro/proapi/role/enable"
	roleInfo "github.com/77d88/go-kit/server/admin_pro/proapi/role/info"
	roleList "github.com/77d88/go-kit/server/admin_pro/proapi/role/list"
	rolePermission "github.com/77d88/go-kit/server/admin_pro/proapi/role/permission"
	roleSave "github.com/77d88/go-kit/server/admin_pro/proapi/role/save"
	userDel "github.com/77d88/go-kit/server/admin_pro/proapi/user/del"
	userDisable "github.com/77d88/go-kit/server/admin_pro/proapi/user/disable"
	userEnable "github.com/77d88/go-kit/server/admin_pro/proapi/user/enable"
	userInfo "github.com/77d88/go-kit/server/admin_pro/proapi/user/info"
	userList "github.com/77d88/go-kit/server/admin_pro/proapi/user/list"
	userLogin "github.com/77d88/go-kit/server/admin_pro/proapi/user/login"
	userLoginUserList "github.com/77d88/go-kit/server/admin_pro/proapi/user/loginUserList"
	userLogout "github.com/77d88/go-kit/server/admin_pro/proapi/user/logout"
	userPermission "github.com/77d88/go-kit/server/admin_pro/proapi/user/permission"
	userRole "github.com/77d88/go-kit/server/admin_pro/proapi/user/role"
	userSave "github.com/77d88/go-kit/server/admin_pro/proapi/user/save"
)

func Register(xsh *xhs.HttpServer) {
	dbAutoMigrate.Register("/pro/db/autoMigrate", xsh)
	dbInitDataRows.Register("/pro/db/initDataRows", xsh)
	dbDbModels.Register("/pro/db/dbModels", xsh)
	userLogin.Register("/pro/user/login", xsh)
	userLogout.Register("/pro/user/logout", xsh)
	userList.Register("/pro/user/list", xsh)
	userDisable.Register("/pro/user/disable", xsh)
	userEnable.Register("/pro/user/enable", xsh)
	userDel.Register("/pro/user/del", xsh)
	userSave.Register("/pro/user/save", xsh)
	userPermission.Register("/pro/user/permission", xsh)
	userRole.Register("/pro/user/role", xsh)
	userInfo.Register("/pro/user/info", xsh)
	userLoginUserList.Register("/pro/user/loginUserList", xsh)
	roleSave.Register("/pro/role/save", xsh)
	roleList.Register("/pro/role/list", xsh)
	roleDel.Register("/pro/role/del", xsh)
	roleInfo.Register("/pro/role/info", xsh)
	roleDisable.Register("/pro/role/disable", xsh)
	roleEnable.Register("/pro/role/enable", xsh)
	rolePermission.Register("/pro/role/permission", xsh)
	permissionList.Register("/pro/permission/list", xsh)
	permissionDel.Register("/pro/permission/del", xsh)
	permissionInfo.Register("/pro/permission/info", xsh)
	permissionSave.Register("/pro/permission/save", xsh)
	permissionDisable.Register("/pro/permission/disable", xsh)
	permissionEnable.Register("/pro/permission/enable", xsh)
	dictList.Register("/pro/dict/list", xsh)
	dictDel.Register("/pro/dict/del", xsh)
	dictInfo.Register("/pro/dict/info", xsh)
	dictSave.Register("/pro/dict/save", xsh)
	dictTypes.Register("/pro/dict/types", xsh)
	menuList.Register("/pro/menu/list", xsh)
	menuDel.Register("/pro/menu/del", xsh)
	menuInfo.Register("/pro/menu/info", xsh)
	menuSave.Register("/pro/menu/save", xsh)
	menuMenu.Register("/pro/menu/menu", xsh)
}
