// Code generated by xf. DO NOT EDIT.

package proapi

import (
	"github.com/77d88/go-kit/plugins/x/servers/http/xhs"
	dbAutoMigrate "github.com/77d88/go-kit/server/admin_pro/proapi/db/autoMigrate"
	dbDbModels "github.com/77d88/go-kit/server/admin_pro/proapi/db/dbModels"
	dbInitDataRows "github.com/77d88/go-kit/server/admin_pro/proapi/db/initDataRows"
	dictDel "github.com/77d88/go-kit/server/admin_pro/proapi/dict/del"
	dictItems "github.com/77d88/go-kit/server/admin_pro/proapi/dict/items"
	dictList "github.com/77d88/go-kit/server/admin_pro/proapi/dict/list"
	dictSave "github.com/77d88/go-kit/server/admin_pro/proapi/dict/save"
	menuDel "github.com/77d88/go-kit/server/admin_pro/proapi/menu/del"
	menuInfo "github.com/77d88/go-kit/server/admin_pro/proapi/menu/info"
	menuList "github.com/77d88/go-kit/server/admin_pro/proapi/menu/list"
	menuMenu "github.com/77d88/go-kit/server/admin_pro/proapi/menu/menu"
	menuSave "github.com/77d88/go-kit/server/admin_pro/proapi/menu/save"
	permissionDel "github.com/77d88/go-kit/server/admin_pro/proapi/permission/del"
	permissionDisable "github.com/77d88/go-kit/server/admin_pro/proapi/permission/disable"
	permissionEnable "github.com/77d88/go-kit/server/admin_pro/proapi/permission/enable"
	permissionInfo "github.com/77d88/go-kit/server/admin_pro/proapi/permission/info"
	permissionList "github.com/77d88/go-kit/server/admin_pro/proapi/permission/list"
	permissionSave "github.com/77d88/go-kit/server/admin_pro/proapi/permission/save"
	roleDel "github.com/77d88/go-kit/server/admin_pro/proapi/role/del"
	roleDisable "github.com/77d88/go-kit/server/admin_pro/proapi/role/disable"
	roleEnable "github.com/77d88/go-kit/server/admin_pro/proapi/role/enable"
	roleInfo "github.com/77d88/go-kit/server/admin_pro/proapi/role/info"
	roleList "github.com/77d88/go-kit/server/admin_pro/proapi/role/list"
	rolePermission "github.com/77d88/go-kit/server/admin_pro/proapi/role/permission"
	roleSave "github.com/77d88/go-kit/server/admin_pro/proapi/role/save"
	userDel "github.com/77d88/go-kit/server/admin_pro/proapi/user/del"
	userDisable "github.com/77d88/go-kit/server/admin_pro/proapi/user/disable"
	userEnable "github.com/77d88/go-kit/server/admin_pro/proapi/user/enable"
	userInfo "github.com/77d88/go-kit/server/admin_pro/proapi/user/info"
	userList "github.com/77d88/go-kit/server/admin_pro/proapi/user/list"
	userLogin "github.com/77d88/go-kit/server/admin_pro/proapi/user/login"
	userLoginInfo "github.com/77d88/go-kit/server/admin_pro/proapi/user/loginInfo"
	userLoginUserList "github.com/77d88/go-kit/server/admin_pro/proapi/user/loginUserList"
	userLogout "github.com/77d88/go-kit/server/admin_pro/proapi/user/logout"
	userPermission "github.com/77d88/go-kit/server/admin_pro/proapi/user/permission"
	userRole "github.com/77d88/go-kit/server/admin_pro/proapi/user/role"
	userSave "github.com/77d88/go-kit/server/admin_pro/proapi/user/save"
)

func Register(xsh *xhs.HttpServer) {
	dbAutoMigrate.Register(xsh)
	dbInitDataRows.Register(xsh)
	dbDbModels.Register(xsh)
	userLogin.Register(xsh)
	userLogout.Register(xsh)
	userList.Register(xsh)
	userDisable.Register(xsh)
	userEnable.Register(xsh)
	userDel.Register(xsh)
	userSave.Register(xsh)
	userPermission.Register(xsh)
	userRole.Register(xsh)
	userInfo.Register(xsh)
	userLoginInfo.Register(xsh)
	userLoginUserList.Register(xsh)
	roleSave.Register(xsh)
	roleList.Register(xsh)
	roleDel.Register(xsh)
	roleInfo.Register(xsh)
	roleDisable.Register(xsh)
	roleEnable.Register(xsh)
	rolePermission.Register(xsh)
	permissionList.Register(xsh)
	permissionDel.Register(xsh)
	permissionInfo.Register(xsh)
	permissionSave.Register(xsh)
	permissionDisable.Register(xsh)
	permissionEnable.Register(xsh)
	dictList.Register(xsh)
	dictDel.Register(xsh)
	dictSave.Register(xsh)
	dictItems.Register(xsh)
	menuList.Register(xsh)
	menuDel.Register(xsh)
	menuInfo.Register(xsh)
	menuSave.Register(xsh)
	menuMenu.Register(xsh)
}
