// Code generated by xf. DO NOT EDIT.

package disable

import (
	"github.com/77d88/go-kit/basic/xerror"
	"github.com/77d88/go-kit/plugins/xapi/server/xhs"
)
func run() xhs.Handler {
    return func(c *xhs.Ctx) (interface{}, error) {
        r := request{}
        err := c.ShouldBind(&r)
        if err != nil {
            return nil, xerror.New("参数错误").SetCode(xhs.CodeParamError).SetInfo("参数错误: %+v", err)
        }
        return handler(c, &r)
    }
}
