// Code generated by xf. DO NOT EDIT.

package biz

import (
	"github.com/77d88/go-kit/plugins/xapi/server/xhs"
	proDbAutoMigrate "github.com/77d88/go-kit/server/admin_pro/biz/pro/db/autoMigrate"
	proDbInitDataRows "github.com/77d88/go-kit/server/admin_pro/biz/pro/db/initDataRows"
	proDictDel "github.com/77d88/go-kit/server/admin_pro/biz/pro/dict/del"
	proDictInfo "github.com/77d88/go-kit/server/admin_pro/biz/pro/dict/info"
	proDictList "github.com/77d88/go-kit/server/admin_pro/biz/pro/dict/list"
	proDictSave "github.com/77d88/go-kit/server/admin_pro/biz/pro/dict/save"
	proDictTypes "github.com/77d88/go-kit/server/admin_pro/biz/pro/dict/types"
	proMenuDel "github.com/77d88/go-kit/server/admin_pro/biz/pro/menu/del"
	proMenuInfo "github.com/77d88/go-kit/server/admin_pro/biz/pro/menu/info"
	proMenuList "github.com/77d88/go-kit/server/admin_pro/biz/pro/menu/list"
	proMenuMenu "github.com/77d88/go-kit/server/admin_pro/biz/pro/menu/menu"
	proMenuSave "github.com/77d88/go-kit/server/admin_pro/biz/pro/menu/save"
	proPermissionDel "github.com/77d88/go-kit/server/admin_pro/biz/pro/permission/del"
	proPermissionDisable "github.com/77d88/go-kit/server/admin_pro/biz/pro/permission/disable"
	proPermissionEnable "github.com/77d88/go-kit/server/admin_pro/biz/pro/permission/enable"
	proPermissionInfo "github.com/77d88/go-kit/server/admin_pro/biz/pro/permission/info"
	proPermissionList "github.com/77d88/go-kit/server/admin_pro/biz/pro/permission/list"
	proPermissionSave "github.com/77d88/go-kit/server/admin_pro/biz/pro/permission/save"
	proRoleDel "github.com/77d88/go-kit/server/admin_pro/biz/pro/role/del"
	proRoleDisable "github.com/77d88/go-kit/server/admin_pro/biz/pro/role/disable"
	proRoleEnable "github.com/77d88/go-kit/server/admin_pro/biz/pro/role/enable"
	proRoleInfo "github.com/77d88/go-kit/server/admin_pro/biz/pro/role/info"
	proRoleList "github.com/77d88/go-kit/server/admin_pro/biz/pro/role/list"
	proRolePermission "github.com/77d88/go-kit/server/admin_pro/biz/pro/role/permission"
	proRoleSave "github.com/77d88/go-kit/server/admin_pro/biz/pro/role/save"
	proUserDel "github.com/77d88/go-kit/server/admin_pro/biz/pro/user/del"
	proUserDisable "github.com/77d88/go-kit/server/admin_pro/biz/pro/user/disable"
	proUserEnable "github.com/77d88/go-kit/server/admin_pro/biz/pro/user/enable"
	proUserInfo "github.com/77d88/go-kit/server/admin_pro/biz/pro/user/info"
	proUserList "github.com/77d88/go-kit/server/admin_pro/biz/pro/user/list"
	proUserLogin "github.com/77d88/go-kit/server/admin_pro/biz/pro/user/login"
	proUserLoginUserList "github.com/77d88/go-kit/server/admin_pro/biz/pro/user/loginUserList"
	proUserLogout "github.com/77d88/go-kit/server/admin_pro/biz/pro/user/logout"
	proUserPermission "github.com/77d88/go-kit/server/admin_pro/biz/pro/user/permission"
	proUserRole "github.com/77d88/go-kit/server/admin_pro/biz/pro/user/role"
	proUserSave "github.com/77d88/go-kit/server/admin_pro/biz/pro/user/save"
)

func Register(xsh *xhs.HttpServer) {
	proDbAutoMigrate.Register("/pro/db/autoMigrate", xsh)
	proDbInitDataRows.Register("/pro/db/initDataRows", xsh)
	proUserLogin.Register("/pro/user/login", xsh)
	proUserLogout.Register("/pro/user/logout", xsh)
	proUserList.Register("/pro/user/list", xsh)
	proUserDisable.Register("/pro/user/disable", xsh)
	proUserEnable.Register("/pro/user/enable", xsh)
	proUserDel.Register("/pro/user/del", xsh)
	proUserSave.Register("/pro/user/save", xsh)
	proUserPermission.Register("/pro/user/permission", xsh)
	proUserRole.Register("/pro/user/role", xsh)
	proUserInfo.Register("/pro/user/info", xsh)
	proUserLoginUserList.Register("/pro/user/loginUserList", xsh)
	proRoleSave.Register("/pro/role/save", xsh)
	proRoleList.Register("/pro/role/list", xsh)
	proRoleDel.Register("/pro/role/del", xsh)
	proRoleInfo.Register("/pro/role/info", xsh)
	proRoleDisable.Register("/pro/role/disable", xsh)
	proRoleEnable.Register("/pro/role/enable", xsh)
	proRolePermission.Register("/pro/role/permission", xsh)
	proPermissionList.Register("/pro/permission/list", xsh)
	proPermissionDel.Register("/pro/permission/del", xsh)
	proPermissionInfo.Register("/pro/permission/info", xsh)
	proPermissionSave.Register("/pro/permission/save", xsh)
	proPermissionDisable.Register("/pro/permission/disable", xsh)
	proPermissionEnable.Register("/pro/permission/enable", xsh)
	proDictList.Register("/pro/dict/list", xsh)
	proDictDel.Register("/pro/dict/del", xsh)
	proDictInfo.Register("/pro/dict/info", xsh)
	proDictSave.Register("/pro/dict/save", xsh)
	proDictTypes.Register("/pro/dict/types", xsh)
	proMenuList.Register("/pro/menu/list", xsh)
	proMenuDel.Register("/pro/menu/del", xsh)
	proMenuInfo.Register("/pro/menu/info", xsh)
	proMenuSave.Register("/pro/menu/save", xsh)
	proMenuMenu.Register("/pro/menu/menu", xsh)
}
